apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gotosocial-web
  namespace: gotosocial
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pub.fedishark.eu`)
      kind: Rule
      middlewares:
        - name: gotosocial-redirect-https
          namespace: gotosocial
      services:
        - name: gotosocial
          port: 8080
