apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - ingressroute-web.yaml
  - middleware-redirect-https.yaml
  - middleware-rate-limit-gotosocial.yaml
  - middleware-fail2ban-gotosocial.yaml
  - pvc-sqlite.yaml
  - pvc-storage.yaml
  - pvc-cache.yaml
generators:
  - smtp-secret-generator.yaml
