apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotosocial-storage
  namespace: gotosocial
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 50Gi
