apiVersion: v1
kind: Service
metadata:
  name: gotosocial
  namespace: gotosocial
  labels:
    app: gotosocial
  annotations:
    external-dns.alpha.kubernetes.io/hostname: pub.fedishark.eu
    external-dns.alpha.kubernetes.io/target: jump.fedishark.eu
    external-dns.alpha.kubernetes.io/ttl: "3600"
spec:
  selector:
    app: gotosocial
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
