apiVersion: v1
kind: Service
metadata:
  name: gotosocial
  namespace: gotosocial
  labels:
    app: gotosocial
spec:
  selector:
    app: gotosocial
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
