apiVersion: ENC[AES256_GCM,data:IXw=,iv:RN58PhgWh1Bu5ECQaoVBqaPC8znaMhexkYx/2QKd8UY=,tag:cHb5KhsxvzPmuWHwBsdd6A==,type:str]
kind: ENC[AES256_GCM,data:RqsoW/Jg,iv:MccxT9MV0+uS+e35cMbkryOcnQsfqxtNDfkxNWGLa50=,tag:USrxiEzal9oC2MAS58kPPw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NRNlWBKsd58UZ/Uk61uA,iv:B5Gmj0zpm253prNXM4uNnk6eO4bmXtXndWgaTDvBN0E=,tag:kDbBNhRzAesQQ19/gXfqmw==,type:str]
    namespace: ENC[AES256_GCM,data:P4SsRrs3YkURNw==,iv:djRIifOgLjnNgA4DLTRC3yjIk2KxwZU4NEmT8QiUatc=,tag:UERiywpghQMKJEQhnqTYYg==,type:str]
type: ENC[AES256_GCM,data:+SkzKxUr,iv:Q83flrfARzZfRjMIMuqw0yxsfA628VmgrC4hAaWBZbo=,tag:wRIpHSCnUG30uQLOYsAWGQ==,type:str]
stringData:
    smtp-password: ENC[AES256_GCM,data:AN/AT1WgecJvlfM0BkWqfeqPfqQiyRpWFEigRbAZCG/HEXTq,iv:dfbBEeFc7zQ/j3qjoryDj7XKr+uGdg9TbfF64L8pf7c=,tag:S0LjWQOeUw9HIUbxuWGSew==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZzlxTW82RnBmMnNLRGQ4
            cy9SZ2pIOXdrYTdzblNQbmJ0SmhtM0c1TnhrCnFLMUw2a2VXSDRuaVB0Y3JEL3Vz
            K3hCejc5NG03QnRKM0NjeGxaek5BNTQKLS0tIDA4eHZ4VU91eVNqczk1ZURENmR3
            SDdlUTFUYjV3L1ZqYm80VTRlSmp4QlEKl3GRJB1iyn0iqP5RlOFk7uXrVWrKvwB5
            MdHLpvIMateKnETLXLf5f9XcdGKv77mlE3ZOBTHt3f53T1VPP6WcBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T19:43:35Z"
    mac: ENC[AES256_GCM,data:/2OUlmp4nou01oANDGrkE1MrLVuMSR3foLh4YXxYI14XO8lKn+1Nf3FJGa+ni+Z+RrmlD1dfDTrL8FuF+jgks/UccapJoZ6j00R7j6GWaadauwot5JM8qBoUDPpMK4zX4DreM7xtZQHCGOBl3adwpxyhz4qeAnNA5YBU3FNP0xw=,iv:i6GqWR/XqZUXyLJQNyBo7HuezZCaZQMBpO27AmagYoA=,tag:V0AEky4u/p3Su4297dfGmQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
