apiVersion: ENC[AES256_GCM,data:0fY=,iv:Bt3mluHLX4eYq3PXpzIlks3/02y4Agy1dwQ5HvyfX7I=,tag:EDXFCO2RDZkfQiZUxbQFYg==,type:str]
kind: ENC[AES256_GCM,data:H8sEHuvX,iv:XFuyGgmzk5AhnHtl9ior6EUwMT27OG/xO0IP2hDka1I=,tag:KTc7jfr+OU4gQAAcuBts4g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bL7KLJfMFMW1AxVhQmPc,iv:v8e4IHBWO/HgUjXYMLFNF9hLgii03Oq0uDvJqXFSLxQ=,tag:EjGQYiObAaGTQpaopJoN6A==,type:str]
    namespace: ENC[AES256_GCM,data:UQDrjHwVug==,iv:+y0k75e5bXfroEmaxBGj40KnVvPIB1T7pvhiHRSp3CY=,tag:q+558bfKiOvweuUmI1iFoQ==,type:str]
type: ENC[AES256_GCM,data:NksETxE+,iv:iFX+oD8iE57MNYjzUjvij6CSz83AJI0NLk5yjgXuwjU=,tag:pLAhywytmC4/BjG7A1LLKQ==,type:str]
stringData:
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:+b2OsMMXAsYVz2Ljfjhzqfkc/B3jdEi9V5V6saKuqsZhMzdVjJN9RHg10nFLTwFCG3vHS2/23Uep0CPXBv4UWQ==,iv:mlYidVMIbkrggdbsCs88HZwDrutZnqKsUY97OIXbZl0=,tag:8nFovCSnk3yWC674zq5zFQ==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bFlUWUo4cXR0OFBvUStJ
            TE9SN2Z4dGtlVHlybkdRSU1kS1ovZTJGeUhvCmZKR3JtcTdiRUplMFFaRWZUNThN
            OFVzL05xMjhObXdweXU3bGhPU0N0UXMKLS0tIHZmUWIrRnNpSHkxL2NYRm43YTFM
            dW5UU1hHM1M0aWVDUDhhSncrUGw1anMK7PRSGAwQSDKujT8UyuD//d25EAjnZyRP
            Kjr5JVMy76y4/gg7faPfnhLFeMehLw+0fCKhLb7PpZiL5VpQNAmV2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T22:29:20Z"
    mac: ENC[AES256_GCM,data:3QfTvTCQcNb5J8zKsJdSyS1a3qTymo6YyQ4uKDW+xRmwysLWDeFqmii3YvvzHRs0hFEPbPNgJfrJtwEE2stJGvAyrRKlrAC0WGWNlm2ZlrLXI3PL5AH+BucnvLhsG8OeY5Xyog5FA4M1gSTtF00k6c/vK/55JzQA1ycYzEm+Jr8=,iv:126wdQ4WY+pELGXolecvT93MVpb6VVihMAsg0yVx+qQ=,tag:QWwll9dCZPUy9Z2mkp0R4w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
