apiVersion: v1
kind: Service
metadata:
  name: vikunja
  namespace: vikunja
  labels:
    app: vikunja
  annotations:
    external-dns.alpha.kubernetes.io/hostname: vikunja.fedishark.eu
    external-dns.alpha.kubernetes.io/target: jump.fedishark.eu
    external-dns.alpha.kubernetes.io/ttl: "3600"
spec:
  selector:
    app: vikunja
  ports:
    - name: http
      port: 3456
      targetPort: http
      protocol: TCP
