apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: omni-tools
  namespace: omni-tools
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`omni.fedishark.eu`)
      kind: Rule
      middlewares:
        - name: security-headers
          namespace: traefik
        - name: rate-limit
          namespace: traefik
      services:
        - name: omni-tools
          port: 80
  tls:
    certResolver: letsencrypt
