apiVersion: v1
kind: ConfigMap
metadata:
  name: asf-ipc-config
  namespace: asf
data:
  IPC.config: |
    {
      "Kestrel": {
        "Endpoints": {
          "HTTP": {
            "Url": "http://0.0.0.0:1242"
          }
        }
      }
    }
