apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: asf-web
  namespace: asf
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`asf.fedishark.eu`)
      kind: Rule
      middlewares:
        - name: asf-redirect-https
          namespace: asf
      services:
        - name: asf
          port: 1242
