apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asf-config
  namespace: asf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 1Gi
