apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: muse-data
  namespace: muse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 2Gi
