apiVersion: ENC[AES256_GCM,data:BOw=,iv:N2LG5oysSQu/v5socH6Idyree2LrH+eo9rWw/fGT8AU=,tag:aHMaxuM/aqmBWsTmYCgvUQ==,type:str]
kind: ENC[AES256_GCM,data:hSM/6nL9,iv:8VI6C6bCdByTb2zagryVCuqjU7XcuOAx7i6dE/nOVZI=,tag:IQQ1F7M3x0TyOFKVEuLS3g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CtrnfnNgq/14iOJj,iv:o5NKXFCm/SZwehFPZg8Z4W6yPn7YbKYq3Djza9rFfwA=,tag:FAOUBpcZIFH4SVIDjUgoEw==,type:str]
    namespace: ENC[AES256_GCM,data:sdO/3A==,iv:XLUgPlqryMZgDefniQ2U40N4XQLzNOBFs3X/9jJBNyw=,tag:92b3Kh3SMo8pMbC7BbTIOg==,type:str]
type: ENC[AES256_GCM,data:MuTSzvV3,iv:9blQpYYQ4HquvOP4nv6Idv92DSt23cRBpoEb7sAc7s4=,tag:KNRd8CdwZEYTkNm7VZoUrg==,type:str]
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:SopkV8pN/QqnBFVMC5pFz4wIPa5H36obm0EUdRGrQ8PbPma8aoVWVRj7YddGJw9ZYoJOHupDdUsNbjrXaMT3SFC7lg9y+UGL,iv:qwXonOmqAAsMaKaLoZcnPMtrFb3xM+WgQN+ZlUmRgmk=,tag:lxIBgFHgGTUUH6w5pFRzQw==,type:str]
    YOUTUBE_API_KEY: ENC[AES256_GCM,data:q4IwDdvL5qNWe3TbsE8kimcjKeSQd2Ms4P71bw/nGQmNSOqKUFKV,iv:OMCFVfeLwl4eFGXRtLnwLGOwLU3m2z5PMpIfmCAEJUk=,tag:Z+JX3Pj0CVXPaPUZn8+JlQ==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:o2qI96bw4WK52MT6E7+lwsBW0sPG6ZKhtPjCtRa8lBQ=,iv:GaeojiiafqWAV8U9dvf1UDbS7annwxRQok2/gHaoq/0=,tag:LhJkG6Z7HsB8F97/CteBCg==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:ek3lQCH/jeVe8DHTcpF91MGBOqxx7nUKLdjpVOvsqjY=,iv:HhHzEtGIK6K2stCqe3cccDGv7btubSNW+PJ6F6rSrBQ=,tag:7PmDWKIsDU7wNrTYQqHeKw==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWERGaU40aklKZ09idFpQ
            SkJVMHRkalloTlRpNDVROVp0VkZWWXNRWTBRCktoWDZQTW96RFFOTyswUlpPaDdr
            eHY0NTFFU3FIL2c2bkFIVjBBaDg1V3cKLS0tIFN0YlRWbk1PTDl0SWdlbW5XOXcw
            K1ROdmVrVEdGSFh0UHd3UXEyckwrODQKa3xRETer2Z3B5/OnN3w4ShnEtEZdYGWw
            KHHolf9zziaDIewAQGVikFro4Ehyp4h3wdA9M0DFxES+fWeBnZ97lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T22:30:59Z"
    mac: ENC[AES256_GCM,data:3vS1XBj5hd2r8bvEcdgAsoT5cYoMX9viMvcbEak9fL/NYpEafP+KyE4rVde3fNhO/QwbrnSKnM8CVoFvVFJuXsaowBM3oZhh0D+/3O5LySHso0Bhm1wQWxh7zLmgygJVPmD+7YeHQyrNPAsV1YwGAit2YK15Eoej4wIqUjRTV70=,iv:K3AgdZhnm16gDkLLfQ/pnpxry49hsqvlmcwecBuY1T4=,tag:KJOpFQnXXudYbL8sK4a8yA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
