apiVersion: ENC[AES256_GCM,data:vBI=,iv:pvNq0/5crU9qvL/7a/x52zZp2OnvR2ZQ76AMseOQzYI=,tag:kGpUJUfzcKTa/vzZC3WMoA==,type:str]
kind: ENC[AES256_GCM,data:M/rlMY+W,iv:eVv+vtsJ5HfCdibYb57eniujlpfVKut0/bWG0U5z3uE=,tag:YP708HamDGWOTzLrSkabzw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wyMBEsxB5N4f9+qgqQ==,iv:RyjoxuBKL85qVNjBwSgQ8jX2NknoeNATLAmoBSChNck=,tag:bybrr5ON2itev5le8AbPUg==,type:str]
    namespace: ENC[AES256_GCM,data:qLMbCXfgdtfGSg==,iv:gYM6VOp1NOHU0Jy4rDs6SsztmUHhVW2NxUARg/96B2c=,tag:okoxV/AHtY61Ex9hbue1KA==,type:str]
type: ENC[AES256_GCM,data:2PjuXAxv,iv:tosxBwiJ+qLcl3ZbcFGhszKa1/0rlwVdKkjHMcjvAHY=,tag:KhcRNF5IN90xIzoNSrnEnQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:0rBSYUc=,iv:BaMC/AXsFRoI+upd8EYbnhoUG2kVr+juc6VhvoI2Mi8=,tag:+ZPLYptehLjNQh3NY5RIBA==,type:str]
    admin-password: ENC[AES256_GCM,data:fSWQYq1GtTXRlPJZg2SlYokxTF7rOVKtrbttKF21x2o=,iv:8JYSYYTkm8S68S2bet9m8sl2apyN5lustvVPNBMODl8=,tag:21tJgQHYDir7p+1Kr7W98A==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydXkyUThtOFdBWUF4ZmVj
            b0JMSHdHNWR4S2hKdUg0WS9NUHJ2YlFHRGxNCm9BeXJlY2srNHc5bVkvVzVkOUN5
            Y1pZcWwyOUJWOU51OXk2VWMzZGhkV28KLS0tIFhCd29MRTkxeWswT2NpRTE0OTZz
            UnpvakE5RVhzOXBkTnN5MFIyR1VUQ0UKTvTE8Sr7TRVz+FmsBhNj+LdfAG2Wc7Vx
            r+Ok3Ws+OWsShOrIquc7vdmqeN7yV0EIRD0cmKPr3ED8es9Yn5Iojg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T20:06:23Z"
    mac: ENC[AES256_GCM,data:4ZBcTjkXiUGUwmgxwDQBuj4PR2vMiNU9n7lzyq38l0HZFxAO33Ef+bXo0lJB3tPoKNKRYe+x1ZTJ077nnuT2ylak6sHbuIHbCnr0KM26CH+LxxblUGSKUomBAlsyW/wA9j2ppcxBoDnxbYRYAE06tR29xG1ZhnrOLsddYVAXxPg=,iv:+KPNnEZfwbyTHp0/vLYYRZ1ssynL8SmYYJZIeY+OqBI=,tag:iO/ccanFlDCrnN+iLLgkVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
