apiVersion: ENC[AES256_GCM,data:TMY=,iv:yKJsVqkGPbR9Oq3YH29hPgWeiuF02WzlJCvcmYHYsVQ=,tag:URz4tLDWvvrYHPfajXPoRw==,type:str]
kind: ENC[AES256_GCM,data:IMx8/oqF,iv:ytR3PhfyZkYaItgQUvofMaj/ZmMDyNWkpv9Zl4fMGps=,tag:PSqZZPX8KsHEeh++Or6/Zg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3Yc4TuYnWtW1/2GtEAo=,iv:aitxf4Z+btIb/56N0RGkXV/ajvtqrx3Ux3EKBN82+eM=,tag:iZQwM9Iv3pd0+7Zgbl6tsQ==,type:str]
    namespace: ENC[AES256_GCM,data:bxywumO0b+nG,iv:z3PpkKWYG/5BwH2YEBJ3Oacy8KbfQvsL4+RKclIVN/A=,tag:6HUDBP8NSlUxEkpu0DeOkw==,type:str]
type: ENC[AES256_GCM,data:BqoZI9ph,iv:Kf2d04JW2AOHCBdDVcgi8P8Xudjb+hYA0ZDViKD2kQE=,tag:OVa2IAoSJa9HsdtNj1tXgg==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:r7bjUDeZKTFOYbOtn8iwDcc=,iv:MHkgvgboxcPaBxMHv79UHI9FVuZ4m09eurJ0jvUWglM=,tag:GUVl8UWejzIyHdOAw0zThw==,type:str]
    client_secret: ENC[AES256_GCM,data:EzfsI9QG84B2OFvLppE/NLrpQmbkV9HAqUsEgDuJ6mrwbNAgmJMcN8t127FFKP3VusR4JaJg2PRqqyriy5QG,iv:lVj4VIovWuT5p+f4rpShwNDS81fC5sc9m1CSoaCyOrk=,tag:+pkwgdSwBmhjvX67CQiR2Q==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZitYa3RQMERIQ2dSSWgz
            UVZ1eG1ENVlqSFdud1VhcENhM3lJL0dLVUUwClVWMkl3aU9nRmRlNWx1SXo2T2hV
            WUZmQlhRbng5ZmhKRmI0L2t3aDMyZTgKLS0tIEQ3d0pCclIrVlJpOVo3TGhrQS9i
            Z2pvaWlKYTVwbzBBZ2tRcENNQ0xjRDAKJSqVRB61cIZ6EeiwDM18JDaVVlSBEZW8
            iFQxJBfzvcZgCNuvb5j74JAKqfiIwWdaIc+QeoL/uYWRzzVSHO/IZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T11:03:04Z"
    mac: ENC[AES256_GCM,data:I1DE8XTkP5L9QodVhxGd/8HgukVfTSs7EFZkWZBYn8zaybopH53Ha5hYv5YVLmVZHcQ9Pvcb1xjXfQzNVzaWxUgCjT+ln+Cbhb2pV/cN0pGSDnaXcYBQwB1Xa33jGy7ITmnE++Q0fqh+NgA7xc1F8rlgaf9HF6WrV4hdZm8fUPc=,iv:OVPC2jzVeN+XhaZ6pb3O0MNoYpPhOi8Lyg1BBLgOEoE=,tag:i7Ue4kc7yNjAj2Ra8c6Htw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
