apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pv-movies.yaml
  - pv-series.yaml
  - pvc-config.yaml
  - pvc-movies.yaml
  - pvc-series.yaml
generators:
  - secret-generator.yaml
