apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-movies
  namespace: jellyfin
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: smb
  resources:
    requests:
      storage: 1Ti
  volumeName: jellyfin-movies
