apiVersion: ENC[AES256_GCM,data:iHk=,iv:E2K5MgexR1WCwlQaYOSTARDFrXFRMnCXrjjA+94NdjI=,tag:SUJQPp68SmQLffpm8iCfQQ==,type:str]
kind: ENC[AES256_GCM,data:KZdoHdwe,iv:wYn2JVIpHOwU9IrqI+WOk1zG7RLrcdA9U68NcgSuuWQ=,tag:VGzGS/GOJAFp0Yj417cHOg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vZiKYalIp6NVqFDQHRmc,iv:q0v7IKiX2csEA2mTlpZCfLPln/h+iZThJccySAn7Jgs=,tag:vGX7FrrttrxKGRURbfFmFw==,type:str]
    namespace: ENC[AES256_GCM,data:b86Xty61FQw=,iv:Mb1mmIBjngWiMQWzo7a75JZCzUIvCM8y3Vv6323aiVI=,tag:9Pr7PYpF8ZYgGhMnatg2Wg==,type:str]
type: ENC[AES256_GCM,data:rtTxwlzC,iv:odO1p4W9Y14tGMZuUCiIqUHW3zOlKLWrIuTH01CqI9o=,tag:ktVLpJxpPEOhvJJTCsEcNg==,type:str]
stringData:
    #ENC[AES256_GCM,data:8AQOqvSh6twehVANi9Rjs1lPJsJoj/mL1+O8fgT/vW3kNLq/XJd1UhxaCJE=,iv:SahC9tUIX07P5tugXWnrUq5QMaw+BmLPAk8XgLncKrg=,tag:ZTt7kFhs0UAp0bGAWt7Tyg==,type:comment]
    #ENC[AES256_GCM,data:b3mLYaiDUp87cTdsORyautlA113wjPfocHzGht5v40rWgQD+fKTtG9WLxykUublxwgB3df8r,iv:yd9F5lXNPh50+/3G+kFcMwe+/iWPx5IEGkOr0MXJry8=,tag:5BwO5pXUrVwOCFMN1dX65A==,type:comment]
    username: ENC[AES256_GCM,data:xO1CpxwzFm0=,iv:dXcNJpZ/EMTIq+cOUuTP9pZzTB8eRZoRwCFeMVishoI=,tag:b5NxPw1CCJtCe+WlVRyVjw==,type:str]
    password: ENC[AES256_GCM,data:qljXa4gpwR0=,iv:YSV83oQ+zA8oA0fjU5dtluVnt3SHNkdhuaw0jJMaCG8=,tag:0Q04xwOSlpidRS0A7kiz5A==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRklnTzZWZHpjZnFDZnE0
            SjNka1libjV1bmw0RlVVbllVbGhRSGJ2V2w4ClJrTGZpNWkvdXJRU3prUnNtMEow
            L1dvYzl5d0hzaG53UWNjeitVMTNDSFkKLS0tIE5mUkZaK01HN3o0b1dBVEZHaUZ0
            UVlVQ3hmbGo3ZVA2OVJieXZhNk1sY3MKxuNVb74SPjKaBaLLjd5AYtbTo+LjCkzi
            Fxn6UKYAQoE3CqByioW3AToHd6XiJbAu6iVOCPmVpdaBswKpWknvTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T18:02:24Z"
    mac: ENC[AES256_GCM,data:zG+IX29zBHZ5pn78vyx0CvtGDKrghC4Jw7ONuwvEafFHPusPwg0QhOyLnJ2JlBhRyDACJaASWs7ty2t8qU7oJr3ipv6KlsAExXGKRtLPmma1EeOGRqfVd+xEyVSUkz4hcPOVy8A5loKWHwm2/aemPxt1z95PgP/W5YxD/iMMVXA=,iv:62R+u8ESjo30+Rs8bE4pHcgnvCZtO4gUfeAbg835VTs=,tag:dLu80VXraeqNqk6MWsvdTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
