apiVersion: ENC[AES256_GCM,data:PtU=,iv:LmuRettg/gkDpo3n6YW3hxHfjUQbEoshXwz0nF5yfOg=,tag:K2rwO3yPVWj9eFAe0dxQJg==,type:str]
kind: ENC[AES256_GCM,data:Hb2WwYA4,iv:MNOMe2FWJOQpJJ3sFPjDYMbLrru+ZdwXJxcwOJQh5VQ=,tag:jzJwFpLicV+xhr4yvq4MdA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:x2CMcyzmWbd2Uj2TSFR4,iv:1etjbV+/g/i6Q+TzoWvQ6OhuAhJ5BOexf3v0XqAMd9o=,tag:XHH0oBXntdnLTcGeaxq1pw==,type:str]
    namespace: ENC[AES256_GCM,data:VYvI5r4VqvI=,iv:JlxNjlWWy4SNxZ2lZFw0BK4AWRGuil0x5iZO04eT50w=,tag:sVbR2W8hAz7QeocchvhhPw==,type:str]
type: ENC[AES256_GCM,data:GzeLQMOG,iv:XBR6UErPK2x1ZjZgCTkC5vwctuZYTncKzYURTRsWMak=,tag:f5RsbcA3c8s8gV1qi17TkQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:6gp6KhDIoeQ=,iv:ok8PWbUn6elhuofr5IBzMP6kgxW1vCbQXz99dt32ugM=,tag:PdueM6R1FPoFdpoTA/LsHA==,type:str]
    password: ENC[AES256_GCM,data:HdXlZ9OT0mxrk4VrVYoH,iv:U0VGu/xsou41AgZZ1+970M1YJBh++QPM3QOssTpJgOg=,tag:BkYJyc4bmMh+kcsWBSmqew==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzKzdsNFBYVERiQ3FBRGpP
            WEhQY2xoU003WXFWdzhsOWdWR1pqUjR0NVdvCjBhYUpsSWdLa2hMbCtGZ3o1cWVI
            WWRISkR3WlowbjlFZnNXSGlqMlFzb3MKLS0tIGQwbjNWbmNVejVBc0Q4UXZpbUFs
            UnZBQzRVNnpFT0s0b1JxcnpPbmZWRkEKQAg2d2W7FsQN5Slb5ialvdeXMP8CgtMM
            K3HTJYZsgZxlzi1BgW5yjv5i9sx97LUV/pY9C9BXv7M975JpB7Q/NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T21:51:27Z"
    mac: ENC[AES256_GCM,data:JjlX+o5vPwVUw+xg+f8k8QFUItBj92lVTZfKFT/Tu/gtx7ZiGD2BCVDn7ZEkVLrcZoOjfUZ7ltkY8yq9wZ5zKONAFeSHJBZ1CsUsvW9O8dYFM8SCL5e4DPlFl57Il23HSCqsmmDxm4t+EXGrTVBrP7WsyYi7+IbIa36FAPAbID0=,iv:oVnZSPACP5WYQEiRlkJZSCi9m5IAN6RAG6HpfDp/BqY=,tag:x39SebM8HRL1e98eIycmWA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
