apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
generators:
  - secret-generator.yaml
configMapGenerator:
  - name: tibber-dashboard
    files:
      - dashboard.json=tibber-dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
