apiVersion: v1
kind: Service
metadata:
  name: tibber-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tibber-exporter
    app.kubernetes.io/instance: tibber-exporter
spec:
  selector:
    app.kubernetes.io/name: tibber-exporter
    app.kubernetes.io/instance: tibber-exporter
  ports:
    - name: http
      port: 8080
      targetPort: http
