apiVersion: ENC[AES256_GCM,data:0Zc=,iv:2gtN3pigQWJUVBmNc+1OhIiqZZvwZ/wYLNBTWlGPdN4=,tag:mSqQ6n/Uv3ljMoYOo4uKIg==,type:str]
kind: ENC[AES256_GCM,data:MEyhbp/f,iv:7rQrX8YakC6xIj8dY3QNDcnErhcQBVESLazSTzdJkdA=,tag:3XqUztAMmt5bSulRse4+Ow==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LdDaASzcW/At3A==,iv:C3pbPuhJld8JakrJ0vEhMC0T5mxOuErXRCBcQWoWxY4=,tag:Mel1Zma63W1AkdfOd1T1uw==,type:str]
    namespace: ENC[AES256_GCM,data:kiw2xluIlYggBw==,iv:JAMd4HpBuzwFobyF0y87Lv73nL4CtXbAJYU9fCbxAMw=,tag:vyD4KljAT7sZWylieFD92w==,type:str]
type: ENC[AES256_GCM,data:sqTbD2/v,iv:RKrwSd1w2OdJOSzNsaX85wGhyecVk6d+LMVa1zE1A/8=,tag:PzKyRNuOpgfaz9f6sxVc2Q==,type:str]
stringData:
    token: ENC[AES256_GCM,data:BxT/0HnYSLcLV45lANCrQh5fBYOJfS16pKkbThRlgDnsDrXvQVpvltUEhg==,iv:zFMwjuLVmORwABU0dnnL3yt54JBjiHIY8RxX61TN1Ng=,tag:LQP5+7Z8+J0GR8hynRE/Dg==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUnoxcDRxSmJWa3JDOU14
            ZTVwZXl3ckdkM1E3d1ZuZGs1VzRXUnJSUURjCnRabU5mQW56N2ZNSXVFTWtQWFJJ
            TWtnODI4ZlpteS94TmhBMGVpRENsVHMKLS0tIGc2c1Zadno3Ui9VeUk5MndDRDh3
            bDcxQ1hRUDJVMXFWRXZSdVVNZzYyLzgKkdYDLpVBpPbMabR3YvndcqRALO/ZmeCj
            KfoGXKiR+cGy+RHLO6q62mIKkMX89+R4NGkv1a0IYKnOlCkvM/38Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T21:09:48Z"
    mac: ENC[AES256_GCM,data:ukB/kkXINLgBooG6szF1flMqsH8wkQhmBcoWrhNNDJ2BZHhISL69uMTW42KtTlDCK2xkTR1vdh0R20DQIaqx4f87Uieb6V56V3FwDh7AdxJ0toSU1Yd+ZuVJITp0hFLEFklobBkFaPgljQfPuxjTdn7TgHtEZ52YeA+EugnwpdM=,iv:/7EsknShu6JpKJsbwKB37vLWeqsXLEoysUKPOqYpEAs=,tag:zMXPv/lf9Aj8KmfoPNsuKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
