apiVersion: ENC[AES256_GCM,data:4C0=,iv:jICs12CfDLusGy9BOjOlDOjXI6o4OjMVVlFSwLHtoGw=,tag:kakW2V5fXva1FwTiyTr0Cw==,type:str]
kind: ENC[AES256_GCM,data:qtJwmqzA,iv:XUXHg2FR7N/Um3Yb/Kev4SMJ3KJfbOrt7yY9kt2xfA8=,tag:5bAEJqHiTx0LssNO/wEl/A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/zoGM0CNi5OiVnuGG7FALLxkT+uHcci3UKrSoYqiAVEDPg==,iv:8v9NSaZlTuaKa6WK+Uh0WKr1eAjlctZJPdnSUwU3b5I=,tag:Os2SrOlQogZde8dyF5I4Pg==,type:str]
    namespace: ENC[AES256_GCM,data:AC+CNUBU6gyjovCJG9I=,iv:iylI+A+vpjkNXW+sjZWW+6ThVJ/V3zLqe1x4bh6niks=,tag:ekEKO4ljmQIqHDza9VtgIA==,type:str]
type: ENC[AES256_GCM,data:UGw0a+9h,iv:Zsol0VI7Y+kLOci/4gl4eFT9ogKQA1B0d8y1Orh173k=,tag:Xzeye9305hkKrZLYRNpqNA==,type:str]
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:X3xAbVGXKZjwJkgU7iGkm1u0yvmaTqPFssx1BZW4c4n6UPbBt4x50mUEMpJ0ApnrOz35EJDI5v+3/3v2mmocJdba8hRMUtj2Uu8FZ0Gx/NmYw99ymj+jAX82uQJp6QIXkobQGHWqj/YmykOY4GxTQE+wAh/jiUYVbfA2HX0YHOFZ3TVre/eRC6Ne3esB92pJXIQbtqld91hrsQkI8xwI7K2kiQZrgGeyj2U9XULg+iR5GUjBC/ZgsvKI0PWbBhLmvY5q4zPRnqPVVs/NCUEyFTciOFhEE+IeIibTl/Afw01jswznS5qlXC/q5Hejot/v+PVd2EZsaDv8ip8vuGL8+4NQrmkX0VxMJZpMWYYImt65lMl7bBHOKZ7e16d/SK0UfN0I1bX/UqTz23bwEd4l9J+5U4255rSOTony9gppSphzLxhvEBgXuX0jwQHYnJgnf/Nrbleyz5h9nAp4m9Qgu2MZ1VrntrjCf1wOKME+K7L5Vvbr11V5MdTOw3iMcKHyaWubBIXr4w5U6oJChB8Q0HJCUQkZHuM/XmBlz/4H6BrAPywIeqQyPhkjfjmH2pJqLJjIp/X8aRLdoKFaIdljB5d8T1mhOdwIQUsDzYzfO4JGR2Er0LwryTqi2WCEfPRv2o2hZINKrQaV6RbWc5VPyF8aZf2YNK5cfwbTcpfdbBiBBKrqP+uXKszpRaH/WWOH1fbdnNLp75WUOB3Et0ovHvAo2C6IzQQtNqZSAmUJxmZUx77HlTZgXwIvWvV8kdkujLU5QcUbtTnepJYdTwXBj12vrK9FBHSiAH5CQ+kzvDhXiQs=,iv:l/zj0ctZFhqCmrBjjsF2msfYDDKC1CHMhTHTs0HJYm4=,tag:YiXgzDIrXsNIszW+BXyD/Q==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ0hjNEMxRVlzQnBYTFJy
            SFRtQWZLSitJMXdQby96OEhJdkU4aUhoWUUwCnJsMUtoOFFMcGJlei95bmZOV21Y
            aGZ6am9ZM3IycVJaSWc1OW1uWVZSQzAKLS0tIFdnaUtBQndNdEFGZGV5S1FLS3Z4
            ZW5NMmtjMmhVKzVHa1dWMXZCZlJ5OXcKct9YTxTEcyuo3zuBkTpsYirMHPq6uEqq
            65HxmDktpgV89X/yyM5AS/k0J6oGIT9MFE4aZZEk5S9zkcBnQK9d6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T21:52:04Z"
    mac: ENC[AES256_GCM,data:eOrKEzTIAW/1Fd30Doi93YJOeMeDeqfSROTth+WdP9C8Ph/R0DuXc5pDcuX7FKBoH/yAO9p0lAYaEJNq6CheNn8c66xnwQNxB6VAlIz007RCDNOtIPyNDirSsaHPieyCV5MEIAKEnuX2NNeTnlC4BIpzcsINDlt019cnkcZiHmw=,iv:Td7rA+UJ1J7z6htQSaQPVunN3kTBB12ruflv/ZUWyTE=,tag:LeFbzYUWCHtgiVVWIYjDgA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
