apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: democratic-csi-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./nfs-driver-config.enc.yaml
  - ./iscsi-driver-config.enc.yaml
