apiVersion: ENC[AES256_GCM,data:C8Y=,iv:lvUIwjX29OZ7nCYnGXQhoEXrr/XK9peC9Iai7EmJGmg=,tag:32aVGMRtMLjEzEqEGNqBEQ==,type:str]
kind: ENC[AES256_GCM,data:MZtZXWbH,iv:WiL3WoVluLBfEZQ7sbGmqlgL23P9SBwTD7VZmC/PO5M=,tag:bzqaiXGMQPCcl4kAliiScA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8tmEYdrIR1uSSL7/bBILPUC4tsSjfA==,iv:AhKhpsK8uBA//SpHCU6IJwuUNC/5VIDxFxbeuXhVBhI=,tag:FYAVs836WvpAXj0BulP5WQ==,type:str]
    namespace: ENC[AES256_GCM,data:kUpIdTQVQpY=,iv:+bG3sUdObTuboRIcXg0gKq33h13mMnzJ5KK/0wjxEoY=,tag:cYSKy7dFgSXPwGQ/itUzqw==,type:str]
type: ENC[AES256_GCM,data:bRTJKG20,iv:IeGvh5ebyBpROnDj4YZRYSqzJcnn1eEHmH66ATZp03U=,tag:+C5lIWVc3nbAaVE6Av0/4A==,type:str]
stringData:
    users: ENC[AES256_GCM,data:RfcqldsqTnf66ejuHZS/i/JgrcYkWjtdofl6W1stZFpYki57avy7u3zpFmORQ9EIVK5rkOxUBwb4bXSk3PMWCV3SS2A=,iv:RvbPpO4TlpFVDf+6mzLg2BbFh/KRDydbJTr8n+pM6tY=,tag:BUMAA+vAr29CRsOjUG3+cQ==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTjdhY0ZMVG1VbVdWU0p5
            Q2dFOS9qZGVPcHN2VXVFT3RvaE4xRnpDMGpvCkNUNkVFM3ZORFdVdVF1eDVQU3Nm
            eUgwSTM4aCtDMFJBbEM0bitkUTJFTW8KLS0tIE5Zd29Va2pXY0VpU2JWZGY0MkRt
            ZnNaeitRSVA2QkVQbXNLM1RyWFhiak0K/n79QbmEIBp8w2ui9U8uFco7DlNY6jCT
            I70zOGy1eLcb3+D85xQpTwtNYm35ld4yZR5KynIP4gR2g382Brxu6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T23:57:26Z"
    mac: ENC[AES256_GCM,data:I/5+1KQE+9fJNzJPrg7rRS2YEj0+N/dgs69ay0K9/0Cwmk0EK1yiwDtfuslTbDvfOQV3uiiGADNlMNIkk13jJ5oB/e2upFRivOt1nJZffhaHfmVfaabv1nN/rYjxAwBStbYbAuHv52MwljE074XW1xsGwKUjkvyrPKfUVbvAZxk=,iv:b2qpiW/iT9jBt2e2ZpLUAP5tOiGp3sLrDpDV44CU3pY=,tag:QgnvFouGgf1DMK8VdF1VCw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
