apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - pvc-config.yaml
  - pv-movies-rw.yaml
  - pvc-movies-rw.yaml
  - pv-series-rw.yaml
  - pvc-series-rw.yaml
generators:
  - secret-generator.yaml
