apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - ingressroute-web.yaml
  - middleware-auth.yaml
  - middleware-redirect-https.yaml
  - pvc-config.yaml
  - pv-movies-rw.yaml
  - pvc-movies-rw.yaml
  - pv-series-rw.yaml
  - pvc-series-rw.yaml
generators:
  - secret-generator.yaml
