apiVersion: ENC[AES256_GCM,data:9Kg=,iv:cMHxc2P/ly2bAs6xCHr0+c65F02vNWTjWxDbtH1G/EM=,tag:cbuPe/lbLV8tQVgcTaGdyw==,type:str]
kind: ENC[AES256_GCM,data:ZSbM33go,iv:wGkR+995eqlfxRAvN6pG7TCgagYSaRe6QYRIBtssO+g=,tag:XkCnQPYegDG/3sGh/wEthA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pqI/ALOlu/rAz/QJD82US5H99MAeN+U=,iv:Lxi7myQgQQ7lLWxYJyWn9IN78SyeL2AxeoYZ0pF3wk0=,tag:pckjQ2IKruWNp+D3pklgLg==,type:str]
    namespace: ENC[AES256_GCM,data:ljrrTnoNRko=,iv:HZyG7d+KOx2gAlf5Fk2FxVhtrTAcedzW9jasU+E5doU=,tag:e3UZDj1V+KyrXsjQWkmrjQ==,type:str]
type: ENC[AES256_GCM,data:mBSHtViq,iv:oZisXvib+Jg6XUWH17DkXvP8wkRd46x9NpOcmDlhtns=,tag:RvDAAscdxyIz4V0nWuZ/gA==,type:str]
stringData:
    wireguard-private-key: ENC[AES256_GCM,data:6KciB1OsZFnCXqzTZbZzGScijhvyfxfI4OmXwRBB6e5dpdOaWVfTAcaSoj0=,iv:PFxei18wAFn8vKodM8fbPX2s+imbLhHFS1MgXsAMLQU=,tag:lTyVjgwIlLFtrA5W6k0Hjg==,type:str]
    wireguard-addresses: ENC[AES256_GCM,data:RC05/NHXZrWwTWPhF+WKkW/zkQEQqlM6yxYVj5WBf/6Ka4hPTEyGLUAw2ikMXe0m,iv:nMnKLD/cp5WqlMpzpsjzV7ywo8l5+vpJIwv/6c2Qm2Y=,tag:+yep1kv2eNeoQulXfzQGUA==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMTdZU2R3ZFRLdEFlRkRw
            K0VzYnVWMlBUbzNQYWcwYTFCc0ZLdCszOVQwClZpQXpNQVpOUnNOZm5sQnRYb1Q5
            amhZbXpnenZtYUh3WThHcVRaenJlaUkKLS0tIEVsa0hRZlBVUnl4Qzkyd3VHWDdj
            RjJHdGdqbTFiS041ZlF4dmZ0RHYweVkKjIoK4uVf87OkMKcFJ92I6ZmPRxu7MX0p
            DWTMUbU6gmsWcpdB5/Afs1C01P5YeTXmGHv58XDXX9GJ1a4aEVUmlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T00:02:19Z"
    mac: ENC[AES256_GCM,data:WD2W2jiu1O/F4tQB+YZAni31PNOQYPtLWdS1rzzuhT4onxTR6qK7D3oKhVMABwSBoP49GtZeVh/ckaFzBO5QyakGN2S31fVTLfpClICy8qewjQCVySFOKCd/iuOGxplFdiM6WmVxcFADUjJ4ENieb4uH6FNz3ewHpKSRPxiDUsU=,iv:f4MbwdJpUksUItUdeGmjxIhPHEK3bVpN9DT5b5BjKMI=,tag:MVMYmXAQ4qu1UItEApoE6A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
