apiVersion: ENC[AES256_GCM,data:3Rk=,iv:Q0VFTe6k0lXjvjACKb1ZprUigOVfBJddp2fDBanWUGs=,tag:q9JUxzrP1yOVcYsSR/X3Pw==,type:str]
kind: ENC[AES256_GCM,data:gLY8i80H,iv:ea8IiEFhBkuypbhEgFdG1qqMgOJp6PG/etu/klkva+U=,tag:DRVqsLjKdpWBhGaRIUi6Fw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hVYTIGVI3VMeA6Qg1nSzjk2TUfRjb5I=,iv:poTYWyoxxgOwBmX61CV+j27J1l6yzC4cGvxrqBN7dZ0=,tag:SdKTjn43gZw8kWIyhTBOTA==,type:str]
    namespace: ENC[AES256_GCM,data:ORmOEsXxXW8=,iv:e2JrG/Kuw9ORQqPuGGepnGo2dZQdR9TsgC3t0pmdISU=,tag:b6xULNNPU+WD3vtWpEQndA==,type:str]
type: ENC[AES256_GCM,data:wBKEhrW7,iv:C8ObjV0HIKxpX1OcBaOn/eezrpgXExuyHtIU7+KThQU=,tag:/BnrXS+BpS6UC9hDRhLqbQ==,type:str]
stringData:
    wireguard-private-key: ENC[AES256_GCM,data:e3IIO82fv7XXfw==,iv:vhn4RNgvRk+R/nkq2vtN2noAxBjRU59NBXJFwN33a2Q=,tag:8ib0Pd7hdY5jeTQlewWXDQ==,type:str]
    wireguard-addresses: ENC[AES256_GCM,data:v+TUL60L1IlDsg==,iv:HO+tNzET8li4JHSv4XfO7kSOiwsDI41Ijm9VccubG2Y=,tag:2+UDpI6QO969ceMreLiKkA==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SlArTGZCL3E3RW5NS2hT
            NFNib1JRbGx1YXBaUnZndXdhUGV6bVdaUWdRCklhSEMzT3lROGF2MEQrU3Z1dGsw
            M1VQSnlLTkg4cnpremY5RW1uZlR6aXcKLS0tIHBGcXNrQXc0VEJjd2xjcU12K09p
            MFJrTWtUYVVDUXBnYXdoRUoyV2JEamcKrhz+p4ponnnEE3ZIz7y45EBuESUyg7Vx
            NqlOGCvzP/KhZma8yvRtSPl8Us5H4Z0hIkmAlC/1GmkTJ5auDmezMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T23:47:46Z"
    mac: ENC[AES256_GCM,data:+Xlrh+8V0eWuvKKlviKZKllXxOhz5+HqLJlRXwNY1idFBScwyuB0BmBm7Sw2u7VsrFxid/tLTEnbX7eJtaIxJ28bn6kNNzs9aHNwU1evUrtUxLngawInmKuAxuEJP7+9TRaSH9TFbK3OQCEWXCnfhKTe9ITSSNWxgvnuFbYe4ow=,iv:UjceOv+PBLwyK7bGgvjqZ/GrLns0UsLXkrcUUXYDxy0=,tag:O+PY+cgh4c/CA5dXwQ6TcQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
