{
	"data": "ENC[AES256_GCM,data:jExAckIPbSHrj3B1ra/VbDXSgOT7x7rX4qIn7XwIGPXo7kYu7rDingGOoU2NI7uZuaPq0V6ZwyDe8m9ZiM16EVu94WJNitahW3kg3V7k/Vadqsdkt/EUk+JIp4pmP6cGAp7hbrFztKRD4JePwTvizpQBKCd+gFJow9rqfLNAMulJvXUhnFri6vJqzi51uZvsuqUhS02YSz4Wwwcv9n/iySxPzvrodgak/bo/JtqGUoZpRUhYKkDMT4RQd1rfOcTH/QTPi1VbJJS+EDeF/r2hWVUmcjVBgyYxyeO8uW3D4n00B9lKHeJAStBtDG1j0DCG+NCCQlmlJgOGjafrpQbzL3zYqockCyUxr8Bt,iv:uJNFOXLMLL66RpdtLQjWpvYdhXPb5mnY6Xszzjcj69c=,tag:3YusE+qPUSNfUIZPrC09hA==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y0JxS0pEUkdHelAwUWsx\nWXJLNzh5QXkydjNzZzdXVUY1dENoeWJJdkgwCmVITHcybUl5VnNRTG1WREUrc0pO\nZDMza0h0L2thZmVZZUZjamN3Qm5SNXMKLS0tIC82U2JFVFprdHg3bDI0SXpJVzRl\nUkxLTy9PMjV6OEtGQ1FTMXhsNlBSaE0KlT6MIVMG44yjemm0IgyXoVMKeJd8GOdL\nyNe+pImbFP1VwWyG7EYflWiQqsR3GBEXiRMoYVzfg7y3c0UiR4hgTA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-02-11T23:52:09Z",
		"mac": "ENC[AES256_GCM,data:96oqk5kbFcLaRqC9jBM//cxTtojKqlQ0ntur5jHXUnTl8nWZnrNaFJ+UFAVyB9eNHii/PQp3XM+cDBXFn/7qSs9EYtSuTyoY2mskhiyagrXRad0fjrVPTTiKYXGbD52Ie6WEyXkFhhWxfNP/2xT4ieeUK+Y4hDu3bWL6qI+nMLI=,iv:3gQvOa1843aB8Ve6ceaD2QfkVR9B8opIfAbwvATn1Mg=,tag:CeQ74JbgZsw9d05KWNzwlw==,type:str]",
		"version": "3.11.0"
	}
}
