apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-movies-rw
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: smb-rw
  resources:
    requests:
      storage: 1Ti
  volumeName: qbittorrent-movies-rw
