apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: qbittorrent-vpn-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./mullvad-wireguard-secret.enc.yaml
  - ./basic-auth-secret.enc.yaml
