apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: jellyfin
  labels:
    app: qbittorrent
  annotations:
    external-dns.alpha.kubernetes.io/hostname: qbittorrent.fedishark.eu
    external-dns.alpha.kubernetes.io/target: jump.fedishark.eu
    external-dns.alpha.kubernetes.io/ttl: "3600"
spec:
  selector:
    app: qbittorrent
  ports:
    - name: webui
      port: 8080
      targetPort: webui
      protocol: TCP
    - name: bittorrent
      port: 6881
      targetPort: bittorrent
      protocol: TCP
    - name: bittorrent-udp
      port: 6881
      targetPort: bittorrent-udp
      protocol: UDP
