apiVersion: ENC[AES256_GCM,data:m/A=,iv:Tx4Z8iQU9q0YybW8oPYcaYf0UMfIvT9hxbgQNPy/Qm8=,tag:tzg6Q+g8sM8XJDqbaS9Qng==,type:str]
kind: ENC[AES256_GCM,data:J7suL13D,iv:dLBssqaXatswz3LhN510+9Wr0+DJ3W6SAlYy6hl1204=,tag:usuYhO8O55h4akgRZUkkZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:67LsiPEvpf7wwKH6xsq0uNo+KQ==,iv:oRHUz0O/xfhjLZSsHgzwRqJxDzZq21WLyDGP4v825rA=,tag:B1Macb7I8iDrSoEnNXyTpQ==,type:str]
    namespace: ENC[AES256_GCM,data:bl5UixhQkKhcrAI=,iv:ploEZ6wgZO01FQUxKQSZiQnxHV4mGVoiKKYE6k/sfq4=,tag:Ice9sWEyGCtKgIeadxPp6w==,type:str]
type: ENC[AES256_GCM,data:GirMW6yE,iv:l4IzHTXc1me66hiAzd0ppRhNpGW5geGC0v+43j0/Ot4=,tag:2zRMo3earCxcCBSWyYwxRw==,type:str]
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:kpgaIx7Y4GFoQv9Njvgu9rSnc44ZcttgF1Lib/JvbLvKpBXYMNunJk+3LyTJnmcC+dUmCirLhyoVmAo8RgWvOA==,iv:4ENAF39aWcPK6j4WqLn88ETSqGsqBTMCTVD5ctGDghI=,tag:RAUC8eib1DPtRHHf3IwUdg==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNjRrSGUxSVBZOWxqZEhQ
            OSsrKzduZzZWUlBhTmwvd2lqKzBnOEh5QVZnCkViL3NyL0kwVFUwTjB1N3hWUUJD
            NnkyM0dNMVdTUmtqMnZCS3BQV3V5UVEKLS0tIHZpeXhxdWtNTnpONkduUWcwOGo4
            a1BQRWc0U1hHOEY3WW1hUkF4MGpHNXMK/XKJxfRvoet1MPiCmoZ6zHPbh52v+3eS
            P+AxXnieC3V/x2iL020/nTAZez+EjfPdAq6xdtU7Sct+mB8nrRl+iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T22:29:20Z"
    mac: ENC[AES256_GCM,data:xnBCSkLb2NhIKb3ubebVZe5RSXAhoZm9JKr3QEjg68bxkLb/XJzBfk0SibgQ/6SW8WuJ0cZjubRSSvXyG2wD+k7jXLSzMBPj2JFK3woUSkHgAQdnM/ayihpqMjZBHAwMnDQrCavC8bsrb2zkAaBWKc/3/kc//okdBLKOqGahEwM=,iv:xUU1+3wnhnV1i7ohpL37XAJzhlHQVHe+DmpSEaWqBZY=,tag:9BWRH0d5tfHQI/ri9WNI1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
