apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: fail2ban
  namespace: traefik
spec:
  plugin:
    fail2ban:
      rules:
        bantime: 3h
        findtime: 10m
        maxretry: 10
        enabled: "true"
        statuscode: "400-499"
