apiVersion: ENC[AES256_GCM,data:Dus=,iv:nyi0QPlwD2KrhnMKuRaOXxM5BiufHHX4DQLiIY6ZQNU=,tag:3f5eoNt9dL1ACKLy5Ik4bw==,type:str]
kind: ENC[AES256_GCM,data:/SooJoeW,iv:WPzhAuhKuSYNfzDD5XoKrjJuvDicxYxPX9JxcHbTSO4=,tag:xQmS0BTlh7HthDO1PyqddA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dXOfRuLNE5Ru9aHqf2x5JGHTdy5YMw==,iv:C6Esba5n0qtMtKUo8q9Y6QoOvRZAVGi7ue23DeDKEvY=,tag:hkFPy3N08Y2j+PAVh+EUCg==,type:str]
    namespace: ENC[AES256_GCM,data:E4aemw/KJRJ6gquA,iv:z/ei2B1lkW65PjsXXaVWBmQ4LaJiAP4FxVg2It+u7RQ=,tag:HzT5m8pNsStsAdHP0tYnaQ==,type:str]
type: ENC[AES256_GCM,data:nY0Je1k/,iv:9JA7H6El3PSSx7nBnMA/N2rSYyIyqDoHZna5Wbrw9BA=,tag:CLIF2SG1L7Wu7RK1M590qQ==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:MpflE2v+roNs9A==,iv:fApNk+IJjLJ61dgsLgnJam+YO3LXw/US8Q+nBWNng6A=,tag:0/xBp4a38p/tIp0wgfz6cQ==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVGdNZlhZczJXNzE4RnNr
            ZWhMN08zMVFEVmpmTElWVGNhMklSWTEyV3pBCllRbnhWYWVxRGtVMy81dHArclA4
            aVUrT0loR0Jsa2ErVUtqdFRwNVFkdDAKLS0tIHZES2t3V2FjOGM2STFOT2ZSdWFs
            UjJKRlk1MENjcWhiRnlvcXp4NEdBU1UKs30sihleojUkNXe4T6KDx1KmuT+MwMMK
            d5lROEEckpSXb1zo1hBBEwcqBE5J+MAKSRglRsoMRYzHFOIwx3zbtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T01:06:54Z"
    mac: ENC[AES256_GCM,data:MrBAjlnWIO47Mfzopk5JWbqbmr1LRrYjlKpIsi78mtqnNzAXhlaFEB70iIRmdCAp8xbBgC5HAWJWD3RlMgdRYKheDbq0HZqOt6wUguvRM7UhAWrgmn1KvoSJA1XX1vmRbhqj3mRQdayx1cxyeACZ+TjW5QZ/f/co4nKrYV3BKlQ=,iv:NTxCy7g1vSJe+T9OsbRx4YK6MZ9GyqB4P4vO4asm21Y=,tag:Y7pOXdCEyyJczRHKOwKOAg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
