apiVersion: ENC[AES256_GCM,data:Dus=,iv:nyi0QPlwD2KrhnMKuRaOXxM5BiufHHX4DQLiIY6ZQNU=,tag:3f5eoNt9dL1ACKLy5Ik4bw==,type:str]
kind: ENC[AES256_GCM,data:/SooJoeW,iv:WPzhAuhKuSYNfzDD5XoKrjJuvDicxYxPX9JxcHbTSO4=,tag:xQmS0BTlh7HthDO1PyqddA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dXOfRuLNE5Ru9aHqf2x5JGHTdy5YMw==,iv:C6Esba5n0qtMtKUo8q9Y6QoOvRZAVGi7ue23DeDKEvY=,tag:hkFPy3N08Y2j+PAVh+EUCg==,type:str]
    namespace: ENC[AES256_GCM,data:E4aemw/KJRJ6gquA,iv:z/ei2B1lkW65PjsXXaVWBmQ4LaJiAP4FxVg2It+u7RQ=,tag:HzT5m8pNsStsAdHP0tYnaQ==,type:str]
type: ENC[AES256_GCM,data:nY0Je1k/,iv:9JA7H6El3PSSx7nBnMA/N2rSYyIyqDoHZna5Wbrw9BA=,tag:CLIF2SG1L7Wu7RK1M590qQ==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:GLRgMEqWeussTRHQBsbN9VM1t6yOHpICyduQYIGa46yaPx71miKjCw==,iv:6QpCIoBnn8hafH42FhSJV9gO9jypF6HBh+FNA1YKw0E=,tag:vJQC5y6VYMlVPWdeEep0iw==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVGdNZlhZczJXNzE4RnNr
            ZWhMN08zMVFEVmpmTElWVGNhMklSWTEyV3pBCllRbnhWYWVxRGtVMy81dHArclA4
            aVUrT0loR0Jsa2ErVUtqdFRwNVFkdDAKLS0tIHZES2t3V2FjOGM2STFOT2ZSdWFs
            UjJKRlk1MENjcWhiRnlvcXp4NEdBU1UKs30sihleojUkNXe4T6KDx1KmuT+MwMMK
            d5lROEEckpSXb1zo1hBBEwcqBE5J+MAKSRglRsoMRYzHFOIwx3zbtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T01:09:32Z"
    mac: ENC[AES256_GCM,data:zPlShMTdwKKoccS2SwiEhkplgTRsOvxrxmEUYkII6XQ/xpk3exsjiJCJjMGCRg/nTM+c3edqadqBp7uCo41sZAtIiSsFe64tr1ZRXjTFitMPgu/kuDlSEM1Ux/w/OSN2/2JQZe10RKFNO9hE9zjULAKPvpmfjIRhbU9vLfFIiTE=,iv:A5kkygJoW6zil9YOIJ2W1xC8ayGMtGHTeHOEa94nyBI=,tag:JyUIV2M225N0JO371Jhq0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
