apiVersion: ENC[AES256_GCM,data:V/4=,iv:PAxrd9Ydfdl2xJ+spv3CZo2DwgnV7XF2LJPSS4y79Jk=,tag:WavjfKhb/JKnK05GlpXu0A==,type:str]
kind: ENC[AES256_GCM,data:bOQWtoqB,iv:Rag/xSIxivicLJ8dn1Tk1Bk9rd90zlp6DQRH7J6DUTQ=,tag:jpyqENL6ksfeIyRPsjESxA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4vd0h78W21io6IGFBwFwB3M4vg==,iv:BrsUwCNhQrEu0K/qmgvl2iIyrOkfinwkmPqzk6DeDAA=,tag:oafiIss9J6AOvLNOQIHwVw==,type:str]
    namespace: ENC[AES256_GCM,data:xoYcdZ6sjygG79iS,iv:UGp7SRGeuvfyqO8jKFAsQh0UVBOFxfOPWme/AWztCss=,tag:Bd5BlPDJ0Qc/FzmUQxIpGg==,type:str]
type: ENC[AES256_GCM,data:SirMIiuy,iv:xo+7j1k86IhswD0jpCa5RjbcApnn6/7rX/NIHAEWwww=,tag:BrZmvahLaI8wcB6+xd5FUg==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:tIebYAaSaGgXPqRsisep/3zZTRESQGfad0eLIw==,iv:OdIzfIW+BIWTyKUerMRcM+83aMJoTTuasTGTxf2t4aQ=,tag:uv1SOYmyQusZSf6pCDCCkQ==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdis0cUtxQzhXRDE3WDFO
            YnpGSGN5UEZ4OFBkK1FQWnJzRnZiVGdDVjJFCkJHQ2RkZDEzejhCdVlCRkV6emZW
            MVVBTHZMNVJIa0hvNlFEZktjeXdGbG8KLS0tIFFSNmNlYW5iZFREVmtSYzkyYndF
            WlNyaEo1cXZTRXZvc3ZjaGFmQTFuUzgK/IdarBHCx4PICwFxFFbTtmsizeT0onaA
            dWXsGLVZdKyUCiIry0PfifJFadELsyvjEcLIjCOprZzjK5jzXNZbZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T18:40:53Z"
    mac: ENC[AES256_GCM,data:U3pbzxcG5tvzRPabGEN0EcSSCgqFYkvbWyCRfye8xTyJuaUuFaGTBSq6PfDpv1Q5BpAiRYb+Rri4X6JskrC6cMgg2lk3W6a5tFltilK8n81B8juREkyLbMp7DOF0VSwxylu68NMAc60x3hxqTdxOSap/aUpYMkWB7M45h7iglvI=,iv:0JMJhxhMpV7pM/7rgjpc+G9JAd07YB7/ByxSoqTH0Z4=,tag:2IJ5yw4d8EhsyNfU+5tGRQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
