apiVersion: ENC[AES256_GCM,data:j1Y=,iv:bq06TFnTP2C2hBt4jQXfvKRAIEu+9yWnOSBs9BOkhZI=,tag:z9vT+/ppGw2QrTRpdxUIhQ==,type:str]
kind: ENC[AES256_GCM,data:U/LzhOnW,iv:4o4aT74TCxfrqdkdkEl2yh/SdIuPY9uP3Wi5miEd1y4=,tag:Hl8lSl8eBUb46zuxp4Gwjw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ADPwxoEJeHgpw4lWSAn+D5gGQQ==,iv:3ircNOXHQ1vAXU7d6U3J7+pLkzdu8O622gxj7T6K+JI=,tag:NuEz81/2juIxThbbd918og==,type:str]
    namespace: ENC[AES256_GCM,data:bpodI81J3QRtVGzG,iv:lfBZzV8zg4w+NpOlAmED+w+8WeRIYKSQrAXCOvrWC2o=,tag:guOb0wUNX7VFttiOI79W6g==,type:str]
type: ENC[AES256_GCM,data:XtoU54Q2,iv:tZK8XgqidCIS4Ar3jQ/NbsLSbo/EmDLw+bbzxtUaypk=,tag:PF6qupHkZbsXLDQ2rBosfw==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:z+8PjWxoGa/G4z9LF3d0lXl3KVR2M9cdvBgCcdPdFH1InkVjOHSQbD8O03GlHw9t6S6/iUgTyYbkCc/8ROxq3g==,iv:aLcxiLAVeowAuLzAxI59FoUMoH43+GhYKlKsi5ndoRE=,tag:zIPU+VMMYZF97RGJNvyfxw==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbjVGN1E3WFNGV0VzWENH
            c3NuL1g3MDlxU21qT0ZwL2FFSkZWc0N6aGhJCk1DRUp6UlB0bXlocFpRVVpnQmFE
            Y1NVUm5kMmp4ZFZIUkpMYWpFazRQTEEKLS0tIFUzQVcxRm05d3VjcUFEa0R2dkNs
            NXNlL2UwRzZlbGhEQUhUZlNwQlU0eDAKG9AGfmkVTuxicsJjdRDyAp3aMNt20/sE
            aPDAIv7JaH3Y0arSklTdQEw3+dFaGnSyo9vIHLi8FtA63VT1aeW5RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T18:01:13Z"
    mac: ENC[AES256_GCM,data:pgQjqoPg4BJylb+cd/Z9JquWjRXrkkmBsXA6bo9KwKHmCAT7I4FLiNRpyt9AzlZziHN48tYDBY7C9sJFSZ+tWHjzjLP33CsnTaLpvf9c3eqq2GTvI++5ZCeprZj9ohhaei7ZPDD26z+EU1jhshRQJI2uptLlLij2N/UGv86tWLw=,iv:8hLsHWaWClpNX9qm35X0pTyGZRjZnZ0VJ1PqE1vD9H4=,tag:trsxGsMr7HkaIxLLsS9pAQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
