apiVersion: ENC[AES256_GCM,data:NzY=,iv:g7agF1KLQTlJ8J7+fgKBbEuvnYvGZBXrf067EG0tz9o=,tag:9XCSFSPP+uylD7/1G2iJDw==,type:str]
kind: ENC[AES256_GCM,data:DRbNb1mF,iv:ELZ57guS5eGW7BV74iCVT+l0qlUtHhlLVH8Ip5fLhC4=,tag:rf6hykaBUWj/NYGMVNyTjQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nypqpJbZSi3JmhrXiHnR2OU=,iv:NweoQN4rn/nIhVVyZMkxrWDZnZ0J1UlknS91TegZq+s=,tag:T6GRZl2xnFimzfKYgQfWbQ==,type:str]
    namespace: ENC[AES256_GCM,data:Sc1Qofc+H2fLeYqo,iv:6d5VhxgjY9f99uj4lMgfnMJAMxTjdf+tCD85bonBWUQ=,tag:l2Wo51RGIE+G0rhurMrftQ==,type:str]
type: ENC[AES256_GCM,data:zghJoK4o,iv:enW+sOvwCex9qr/f/I1KXv7ghFNKGHWCxzIN+eAjOAk=,tag:rIZUDFOKkj9t2JscB1EixQ==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:i0UxDp2ZcBGn/pIgP47alaBPhWPSGulExpMaVA==,iv:98yhxqmU3zTgrggHgUAPFpbzPuiZgEfDCWLHe//1M3M=,tag:RUwQI2co7o/0TCQabe4JGg==,type:str]
sops:
    age:
        - recipient: age1uhgqfcm3tfuzv3tq8d62medf04g977zas2hr9wmntc8wjn2e3asqvp7adp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESzJlMlRacHRiRjYydHR4
            WndBL1dhU0JLU2ZtTWhtb0Vza1RJK1N5ZzNrCnVMckxlUVVYaUNrSXByNDdpSnJL
            eXBJVEVYalRaZElZMGNsOXFuWEFXbE0KLS0tIDFUY3U1amtIWGEraXVUdWFjR0RG
            czRLdUJMUWdWL0FIYkpZOEZlbzRFMFkKaPIaIMsHe5Fn9lZyE1LVnzwhNFrYOYSj
            T4Z09z3EyWQTEESppp+eBRVo0E9So1nxZ1q5bYy0JB6jQwnoYwHNzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T18:42:05Z"
    mac: ENC[AES256_GCM,data:h+3EzQcg8wlDW8HRCeWVQ8LkUYK+iPaqattTGxDGgg0TISJj2QipI1cYrkVOi0Ce4T+E+vqaPHXoyzByKNAvhALc/McBTTmqsJo9R6vE6RaAYsD1RZG8G4pWDK1l5KfScWP3ZWGrYY6ickOKxndHL0IaI899itJ4bh3oQEB8mLM=,iv:d/dAf+kDwAvMy0gqFvmyvvaD9lgaa8i8r1szA5ickH8=,tag:DuJ93lH37/54IDaTAtsmsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
